// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bookstore.data;

namespace backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201007122952_create")]
    partial class create
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("bookstore.domain.models.Livro", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("codigo")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AnoDeLancamento")
                        .HasColumnName("ano_de_lancamento")
                        .HasColumnType("char(15)");

                    b.Property<string>("Isbn")
                        .HasColumnName("isbn")
                        .HasColumnType("char(13)");

                    b.Property<string>("SubTitulo")
                        .HasColumnName("sub_titulo")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Titulo")
                        .HasColumnName("titulo")
                        .HasColumnType("varchar(200)");

                    b.HasKey("Codigo");

                    b.ToTable("Livro");
                });

            modelBuilder.Entity("bookstore.domain.models.Livro", b =>
                {
                    b.OwnsOne("bookstore.domain.objectvalue.Autor", "Autor", b1 =>
                        {
                            b1.Property<int>("LivroCodigo")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("PrimeiroNomeDoAutor")
                                .HasColumnName("primeiro_nome")
                                .HasColumnType("varchar(200)");

                            b1.Property<string>("SobreNomeDoAutor")
                                .HasColumnName("sobre_nome")
                                .HasColumnType("varchar(200)");

                            b1.HasKey("LivroCodigo");

                            b1.ToTable("Livro");

                            b1.WithOwner()
                                .HasForeignKey("LivroCodigo");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
